name: Hello World

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: echo "Hello World"